FROM localhost/mariadb:latest

# Retirar credenciais
ENV MARIADB_ROOT_PASSWORD=root.pass.usuario.MariaDB
ENV MARIADB_DATABASE=UsuarioDB
ENV MARIADB_USER=usuario_dbuser
ENV MARIADB_PASSWORD=usuario.pass.MariaDB

COPY UsuarioDB.sql /docker-entrypoint-initdb.d/

RUN chmod 644 /docker-entrypoint-initdb.d/*.sql && \
    chown mysql:mysql /docker-entrypoint-initdb.d/*.sql

EXPOSE 3306