FROM mariadb:11.3


COPY bancodedados.sql /docker-entrypoint-initdb.d/
RUN chmod 644 /docker-entrypoint-initdb.d/bancodedados.sql \
    && chown mysql:mysql /docker-entrypoint-initdb.d/bancodedados.sql
