FROM python:latest

RUN apt-get update && apt-get install -y \
    gcc \
    default-libmysqlclient-dev 

WORKDIR /app

COPY requirements.txt .
RUN pip install --upgrade pip && pip install -r requirements.txt

COPY . .

EXPOSE 5000

CMD ["python", "main.py"]
