pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/Nicolasortiiz/VagaXpress'
            }
        }

        stage('Build') {
            steps {
                sh 'mvn package'
            }
        }

        stage('Docker Build') {
            steps {
                sh 'docker-compose up --build'
                sh 'docker exec -it ollama ollama pull gemma3:1b'
            }
        }
    }
}