apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-estacionamento-deployment
  labels:
    app: db-estacionamento
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-estacionamento
  template:
    metadata:
      labels:
        app: db-estacionamento
    spec:
      containers:
        - name: db-estacionamento
          image: localhost:4000/imagem-db-estacionamento
          imagePullPolicy: Always
          ports:
            - containerPort: 3306
          env:
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: segredos
                  key: DB_ROOT_PASS_ESTACIONAMENTO
            - name: MARIADB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: segredos
                  key: DB_NAME_ESTACIONAMENTO
            - name: MARIADB_USER
              valueFrom:
                secretKeyRef:
                  name: segredos
                  key: DB_USER_ESTACIONAMENTO
            - name: MARIADB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: segredos
                  key: DB_PASS_ESTACIONAMENTO
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-notificacao-deployment
  labels:
    app: db-notificacao
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-notificacao
  template:
    metadata:
      labels:
        app: db-notificacao
    spec:
      containers:
        - name: db-notificacao
          image: localhost:4000/imagem-db-notificacao
          imagePullPolicy: Always
          ports:
            - containerPort: 3306
          env:
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: segredos
                  key: DB_ROOT_PASS_NOTIFICACAO
            - name: MARIADB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: segredos
                  key: DB_NAME_NOTIFICACAO
            - name: MARIADB_USER
              valueFrom:
                secretKeyRef:
                  name: segredos
                  key: DB_USER_NOTIFICACAO
            - name: MARIADB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: segredos
                  key: DB_PASS_NOTIFICACAO
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-pagamento-deployment
  labels:
    app: db-pagamento
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-pagamento
  template:
    metadata:
      labels:
        app: db-pagamento
    spec:
      containers:
        - name: db-pagamento
          image: localhost:4000/imagem-db-pagamento
          imagePullPolicy: Always
          ports:
            - containerPort: 3306
          env:
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: segredos
                  key: DB_ROOT_PASS_PAGAMENTO
            - name: MARIADB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: segredos
                  key: DB_NAME_PAGAMENTO
            - name: MARIADB_USER
              valueFrom:
                secretKeyRef:
                  name: segredos
                  key: DB_USER_PAGAMENTO
            - name: MARIADB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: segredos
                  key: DB_PASS_PAGAMENTO
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-usuario-deployment
  labels:
    app: db-usuario
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-usuario
  template:
    metadata:
      labels:
        app: db-usuario
    spec:
      containers:
        - name: db-usuario
          image: localhost:4000/imagem-db-usuario
          imagePullPolicy: Always
          ports:
            - containerPort: 3306
          env:
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: segredos
                  key: DB_ROOT_PASS_USUARIO
            - name: MARIADB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: segredos
                  key: DB_NAME_USUARIO
            - name: MARIADB_USER
              valueFrom:
                secretKeyRef:
                  name: segredos
                  key: DB_USER_USUARIO
            - name: MARIADB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: segredos
                  key: DB_PASS_USUARIO