apiVersion: apps/v1
kind: Deployment
metadata:
  name: sensor-deployment
  labels:
    app: sensor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sensor
  template:
    metadata:
      labels:
        app: sensor
    spec:
      containers:
        - name: sensor
          image: localhost:4000/imagem-sensor
          imagePullPolicy: Always
          ports:
            - containerPort: 5000  
          env:
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: segredos
                  key: DB_NAME_USUARIO
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: segredos
                  key: DB_USER_USUARIO
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: segredos
                  key: DB_PASS_USUARIO

