apiVersion: apps/v1
kind: Deployment
metadata:
  name: sensor-deployment
  labels:
    app: sensor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sensor
  template:
    metadata:
      labels:
        app: sensor
    spec:
      containers:
        - name: sensor
          image: imagem-sensor
          imagePullPolicy: Never
          ports:
            - containerPort: 5000  
          env:
            - name: DB_HOST
              value: "db-estacionamento-service"
            - name: DB_NAME
              value: "EstacionamentoDB"
            - name: DB_USER
              value: "estacionamento_dbuser"
            - name: DB_PASS
              value: "estacionamento.pass.MariaDB"

#implementar ingress