apiVersion: apps/v1
kind: Deployment
metadata:
  name: gestao-veiculos-deployment
  labels:
    app: gestao-veiculos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gestao-veiculos
  template:
    metadata:
      labels:
        app: gestao-veiculos
    spec:
      volumes:
        - name: gpg-volume
          secret:
            secretName: segredos
            items:
              - key: CHAVE_PRIVADA
                path: private.key
              - key: PUBLIC_KEY
                path: public.key
        - name: gnupg-home
          emptyDir: {}
      initContainers:
        - name: gpg-importador
          image: alpine:edge
          command: ["/bin/sh", "-c"]
          args:
            - |
              apk add --no-cache gnupg;
              mkdir -p /var/www/.gnupg;
              chmod 700 /var/www/.gnupg;
              gpg --batch --homedir /var/www/.gnupg --import /etc/gpg-keys/public.key;
              gpg --batch --homedir /var/www/.gnupg --import /etc/gpg-keys/private.key;
              chown -R 33:33 /var/www/.gnupg
          volumeMounts:
            - name: gpg-volume
              mountPath: /etc/gpg-keys
              readOnly: true
            - name: gnupg-home
              mountPath: /var/www/.gnupg
      containers:
        - name: gestao-veiculos
          volumeMounts:
              - name: gnupg-home
                mountPath: /var/www/.gnupg
          image: localhost:4000/imagem-gestao-veiculos
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: COGNITO_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: segredos
                  key: COGNITO_CLIENT_SECRET
            - name: COGNITO_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: segredos
                  key: COGNITO_CLIENT_ID
            - name: COGNITO_USER_POOL_ID
              valueFrom:
                secretKeyRef:
                  name: segredos
                  key: COGNITO_USER_POOL_ID
            - name: COGNITO_KEY
              valueFrom:
                secretKeyRef:
                  name: segredos
                  key: COGNITO_KEY
            - name: COGNITO_SECRET
              valueFrom:
                secretKeyRef:
                  name: segredos
                  key: COGNITO_SECRET
            - name: COGNITO_REGION
              valueFrom:
                secretKeyRef:
                  name: segredos
                  key: COGNITO_REGION
            - name: GOOGLE_API
              valueFrom:
                secretKeyRef:
                  name: segredos
                  key: GOOGLE_API
            - name: BOT_API
              valueFrom:
                secretKeyRef:
                  name: segredos
                  key: BOT_API
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: segredos
                  key: DB_NAME_USUARIO
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: segredos
                  key: DB_USER_USUARIO
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: segredos
                  key: DB_PASS_USUARIO
            - name: EMAIL_GPG
              valueFrom: 
                secretKeyRef:
                  name: segredos
                  key: EMAIL_GPG
            - name: SENHA_GPG
              valueFrom: 
                secretKeyRef:
                  name: segredos
                  key: SENHA_GPG
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notificacoes-deployment
  labels:
    app: notificacoes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notificacoes
  template:
    metadata:
      labels:
        app: notificacoes
    spec:
      volumes:
        - name: gpg-volume
          secret:
            secretName: segredos
            items:
              - key: CHAVE_PRIVADA
                path: private.key
              - key: PUBLIC_KEY
                path: public.key
        - name: gnupg-home
          emptyDir: {}
      initContainers:
        - name: gpg-importador
          image: alpine:edge
          command: ["/bin/sh", "-c"]
          args:
            - |
              apk add --no-cache gnupg;
              mkdir -p /var/www/.gnupg;
              chmod 700 /var/www/.gnupg;
              gpg --batch --homedir /var/www/.gnupg --import /etc/gpg-keys/public.key;
              gpg --batch --homedir /var/www/.gnupg --import /etc/gpg-keys/private.key;
              chown -R 33:33 /var/www/.gnupg
          volumeMounts:
            - name: gpg-volume
              mountPath: /etc/gpg-keys
              readOnly: true
            - name: gnupg-home
              mountPath: /var/www/.gnupg
      containers:
        - name: notificacoes
          volumeMounts:
              - name: gnupg-home
                mountPath: /var/www/.gnupg
          image: localhost:4000/imagem-notificacoes
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: COGNITO_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: segredos
                  key: COGNITO_CLIENT_SECRET
            - name: COGNITO_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: segredos
                  key: COGNITO_CLIENT_ID
            - name: COGNITO_USER_POOL_ID
              valueFrom:
                secretKeyRef:
                  name: segredos
                  key: COGNITO_USER_POOL_ID
            - name: COGNITO_KEY
              valueFrom:
                secretKeyRef:
                  name: segredos
                  key: COGNITO_KEY
            - name: COGNITO_SECRET
              valueFrom:
                secretKeyRef:
                  name: segredos
                  key: COGNITO_SECRET
            - name: COGNITO_REGION
              valueFrom:
                secretKeyRef:
                  name: segredos
                  key: COGNITO_REGION
            - name: GOOGLE_API
              valueFrom:
                secretKeyRef:
                  name: segredos
                  key: GOOGLE_API
            - name: BOT_API
              valueFrom:
                secretKeyRef:
                  name: segredos
                  key: BOT_API
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: segredos
                  key: DB_NAME_NOTIFICACAO
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: segredos
                  key: DB_USER_NOTIFICACAO
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: segredos
                  key: DB_PASS_NOTIFICACAO
            - name: EMAIL_GPG
              valueFrom: 
                secretKeyRef:
                  name: segredos
                  key: EMAIL_GPG
            - name: SENHA_GPG
              valueFrom: 
                secretKeyRef:
                  name: segredos
                  key: SENHA_GPG
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pagamento-deployment
  labels:
    app: pagamento
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pagamento
  template:
    metadata:
      labels:
        app: pagamento
    spec:
      volumes:
        - name: gpg-volume
          secret:
            secretName: segredos
            items:
              - key: CHAVE_PRIVADA
                path: private.key
              - key: PUBLIC_KEY
                path: public.key
        - name: gnupg-home
          emptyDir: {}
      initContainers:
        - name: gpg-importador
          image: alpine:edge
          command: ["/bin/sh", "-c"]
          args:
            - |
              apk add --no-cache gnupg;
              mkdir -p /var/www/.gnupg;
              chmod 700 /var/www/.gnupg;
              gpg --batch --homedir /var/www/.gnupg --import /etc/gpg-keys/public.key;
              gpg --batch --homedir /var/www/.gnupg --import /etc/gpg-keys/private.key;
              chown -R 33:33 /var/www/.gnupg
          volumeMounts:
            - name: gpg-volume
              mountPath: /etc/gpg-keys
              readOnly: true
            - name: gnupg-home
              mountPath: /var/www/.gnupg
      containers:
        - name: pagamento
          volumeMounts:
              - name: gnupg-home
                mountPath: /var/www/.gnupg
          image: localhost:4000/imagem-pagamento
          imagePullPolicy: Always
          ports:
            - containerPort: 80  
          env:
            - name: COGNITO_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: segredos
                  key: COGNITO_CLIENT_SECRET
            - name: COGNITO_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: segredos
                  key: COGNITO_CLIENT_ID
            - name: COGNITO_USER_POOL_ID
              valueFrom:
                secretKeyRef:
                  name: segredos
                  key: COGNITO_USER_POOL_ID
            - name: COGNITO_KEY
              valueFrom:
                secretKeyRef:
                  name: segredos
                  key: COGNITO_KEY
            - name: COGNITO_SECRET
              valueFrom:
                secretKeyRef:
                  name: segredos
                  key: COGNITO_SECRET
            - name: COGNITO_REGION
              valueFrom:
                secretKeyRef:
                  name: segredos
                  key: COGNITO_REGION
            - name: GOOGLE_API
              valueFrom:
                secretKeyRef:
                  name: segredos
                  key: GOOGLE_API
            - name: BOT_API
              valueFrom:
                secretKeyRef:
                  name: segredos
                  key: BOT_API
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: segredos
                  key: DB_NAME_PAGAMENTO
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: segredos
                  key: DB_USER_PAGAMENTO
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: segredos
                  key: DB_PASS_PAGAMENTO
            - name: EMAIL_GPG
              valueFrom: 
                secretKeyRef:
                  name: segredos
                  key: EMAIL_GPG
            - name: SENHA_GPG
              valueFrom: 
                secretKeyRef:
                  name: segredos
                  key: SENHA_GPG
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vagas-deployment
  labels:
    app: vagas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vagas
  template:
    metadata:
      labels:
        app: vagas
    spec:
      volumes:
        - name: gpg-volume
          secret:
            secretName: segredos
            items:
              - key: CHAVE_PRIVADA
                path: private.key
              - key: PUBLIC_KEY
                path: public.key
        - name: gnupg-home
          emptyDir: {}
      initContainers:
        - name: gpg-importador
          image: alpine:edge
          command: ["/bin/sh", "-c"]
          args:
            - |
              apk add --no-cache gnupg;
              mkdir -p /var/www/.gnupg;
              chmod 700 /var/www/.gnupg;
              gpg --batch --homedir /var/www/.gnupg --import /etc/gpg-keys/public.key;
              gpg --batch --homedir /var/www/.gnupg --import /etc/gpg-keys/private.key;
              chown -R 33:33 /var/www/.gnupg
          volumeMounts:
            - name: gpg-volume
              mountPath: /etc/gpg-keys
              readOnly: true
            - name: gnupg-home
              mountPath: /var/www/.gnupg
      containers:
        - name: vagas
          volumeMounts:
              - name: gnupg-home
                mountPath: /var/www/.gnupg
          image: localhost:4000/imagem-vagas
          imagePullPolicy: Always
          ports:
            - containerPort: 80  
          env:
            - name: COGNITO_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: segredos
                  key: COGNITO_CLIENT_SECRET
            - name: COGNITO_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: segredos
                  key: COGNITO_CLIENT_ID
            - name: COGNITO_USER_POOL_ID
              valueFrom:
                secretKeyRef:
                  name: segredos
                  key: COGNITO_USER_POOL_ID
            - name: COGNITO_KEY
              valueFrom:
                secretKeyRef:
                  name: segredos
                  key: COGNITO_KEY
            - name: COGNITO_SECRET
              valueFrom:
                secretKeyRef:
                  name: segredos
                  key: COGNITO_SECRET
            - name: COGNITO_REGION
              valueFrom:
                secretKeyRef:
                  name: segredos
                  key: COGNITO_REGION
            - name: GOOGLE_API
              valueFrom:
                secretKeyRef:
                  name: segredos
                  key: GOOGLE_API
            - name: BOT_API
              valueFrom:
                secretKeyRef:
                  name: segredos
                  key: BOT_API
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: segredos
                  key: DB_NAME_ESTACIONAMENTO
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: segredos
                  key: DB_USER_ESTACIONAMENTO
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: segredos
                  key: DB_PASS_ESTACIONAMENTO
            - name: EMAIL_GPG
              valueFrom: 
                secretKeyRef:
                  name: segredos
                  key: EMAIL_GPG
            - name: SENHA_GPG
              valueFrom: 
                secretKeyRef:
                  name: segredos
                  key: SENHA_GPG