# Usar secrets para credenciais e adicionar credenciais Cognito
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gestao-veiculos-deployment
  labels:
    app: gestao-veiculos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gestao-veiculos
  template:
    metadata:
      labels:
        app: gestao-veiculos
    spec:
      containers:
        - name: gestao-veiculos
          image: imagem-gestao-veiculos:latest
          ports:
            - containerPort: 8880
          env:
            - name: COGNITO_CLIENT_SECRET
              value: "cognitoclientsecret"
            - name: COGNITO_CLIENT_ID
              value: "cognitoclientid"
            - name: COGNITO_USER_POOL_ID
              value: "cognitouserpoolid"
            - name: COGNITO_KEY
              value: "cognitokey"
            - name: COGNITO_SECRET
              value: "cognitosecret"
            - name: COGNITO_REGION
              value: "cognitoregion"
            - name: BOT_API
              value: "telegrambotapi"
            - name: DB_HOST
              value: "db-usuario-service"
            - name: DB_NAME
              value: "UsuarioDB"
            - name: DB_USER
              value: "usuario_dbuser"
            - name: DB_PASS
              value: "usuario.pass.MariaDB"  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notificacoes-deployment
  labels:
    app: notificacoes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notificacoes
  template:
    metadata:
      labels:
        app: notificacoes
    spec:
      containers:
        - name: notificacoes
          image: imagem-notificacoes:latest
          ports:
            - containerPort: 8881
          env:
            - name: COGNITO_CLIENT_SECRET
              value: "cognitoclientsecret"
            - name: COGNITO_CLIENT_ID
              value: "cognitoclientid"
            - name: COGNITO_USER_POOL_ID
              value: "cognitouserpoolid"
            - name: COGNITO_KEY
              value: "cognitokey"
            - name: COGNITO_SECRET
              value: "cognitosecret"
            - name: COGNITO_REGION
              value: "cognitoregion"
            - name: BOT_API
              value: "telegrambotapi"
            - name: DB_HOST
              value: "db-notificacao-service"
            - name: DB_NAME
              value: "NotificacaoDB"
            - name: DB_USER
              value: "notificacao_dbuser"
            - name: DB_PASS
              value: "notificacao.pass.MariaDB"  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pagamento-deployment
  labels:
    app: pagamento
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pagamento
  template:
    metadata:
      labels:
        app: pagamento
    spec:
      containers:
        - name: pagamento
          image: imagem-pagamento:latest
          ports:
            - containerPort: 8882  
          env:
            - name: COGNITO_CLIENT_SECRET
              value: "cognitoclientsecret"
            - name: COGNITO_CLIENT_ID
              value: "cognitoclientid"
            - name: COGNITO_USER_POOL_ID
              value: "cognitouserpoolid"
            - name: COGNITO_KEY
              value: "cognitokey"
            - name: COGNITO_SECRET
              value: "cognitosecret"
            - name: COGNITO_REGION
              value: "cognitoregion"
            - name: BOT_API
              value: "telegrambotapi"
            - name: DB_HOST
              value: "db-pagamento-service"
            - name: DB_NAME
              value: "PagamentoDB"
            - name: DB_USER
              value: "pagamento_dbuser"
            - name: DB_PASS
              value: "pagamento.pass.MariaDB"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vagas-deployment
  labels:
    app: vagas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vagas
  template:
    metadata:
      labels:
        app: vagas
    spec:
      containers:
        - name: vagas
          image: imagem-vagas:latest
          ports:
            - containerPort: 8883  
          env:
            - name: COGNITO_CLIENT_SECRET
              value: "cognitoclientsecret"
            - name: COGNITO_CLIENT_ID
              value: "cognitoclientid"
            - name: COGNITO_USER_POOL_ID
              value: "cognitouserpoolid"
            - name: COGNITO_KEY
              value: "cognitokey"
            - name: COGNITO_SECRET
              value: "cognitosecret"
            - name: COGNITO_REGION
              value: "cognitoregion"
            - name: BOT_API
              value: "telegrambotapi"
            - name: DB_HOST
              value: "db-estacionamento-service"
            - name: DB_NAME
              value: "EstacionamentoDB"
            - name: DB_USER
              value: "estacionamento_dbuser"
            - name: DB_PASS
              value: "estacionamento.pass.MariaDB"